In [2]:
import torch
import torch.nn as nn

In [3]:
class Model(nn.Module):
    def __init__(self, num_feature):
        super().__init__()
        self.linear = nn.Linear(num_feature, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)

        return out
        

In [4]:
features  = torch.rand(10, 5)

model = Model(features.shape[1])
model(features)

tensor([[0.3789],
        [0.3775],
        [0.3973],
        [0.3766],
        [0.3974],
        [0.4218],
        [0.4548],
        [0.3988],
        [0.4721],
        [0.3729]], grad_fn=<SigmoidBackward0>)

In [5]:
model.linear.weight

Parameter containing:
tensor([[ 0.1282, -0.3719, -0.1940, -0.2701,  0.3876]], requires_grad=True)

In [6]:
model.linear.bias

Parameter containing:
tensor([-0.1881], requires_grad=True)

In [7]:
%pip install torchinfo

Note: you may need to restart the kernel to use updated packages.


In [12]:
from torchinfo import summary

summary(model,input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [14]:
class Model_NN(nn.Module):
    def __init__(self, num_feature):
        super().__init__()
        self.linear1 = nn.Linear(num_feature, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3 ,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out
        

In [15]:
features  = torch.rand(10, 5)

model = Model_NN(features.shape[1])
model(features)

tensor([[0.3730],
        [0.3736],
        [0.3733],
        [0.3738],
        [0.3738],
        [0.3738],
        [0.3725],
        [0.3738],
        [0.3733],
        [0.3732]], grad_fn=<SigmoidBackward0>)

In [16]:
model.linear1.weight

Parameter containing:
tensor([[-3.5433e-01, -2.7345e-02,  5.8146e-02, -1.5947e-01, -2.6044e-01],
        [ 9.9311e-02, -1.9811e-04, -1.4960e-01, -3.6356e-01,  2.8204e-01],
        [-1.3549e-01, -1.5332e-01,  1.0666e-02, -1.9478e-01,  2.2186e-01]],
       requires_grad=True)

In [17]:
model.linear2.weight

Parameter containing:
tensor([[-0.1883,  0.4437, -0.0373]], requires_grad=True)

In [18]:
model.linear1.bias

Parameter containing:
tensor([-0.4235, -0.2685,  0.1905], requires_grad=True)

In [19]:
model.linear2.bias

Parameter containing:
tensor([-0.5158], requires_grad=True)

In [20]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model_NN                                 [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Sequential container

In [36]:
class Model_NN_Seq(nn.Module):
    def __init__(self, num_feature):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_feature, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        out = self.network(features)

        return out

In [39]:
features  = torch.rand(10, 5)

model_ = Model_NN_Seq(features.shape[1])
model(features)

tensor([[0.6755],
        [0.7051],
        [0.6921],
        [0.6923],
        [0.6717],
        [0.6676],
        [0.6639],
        [0.6621],
        [0.6752],
        [0.6664]], grad_fn=<SigmoidBackward0>)

In [40]:
model_.network[0].weight

Parameter containing:
tensor([[ 0.2936, -0.0168, -0.1583, -0.3878,  0.2416],
        [-0.2872, -0.4202,  0.3783, -0.4373,  0.0558],
        [ 0.2471,  0.2004, -0.0908, -0.3819, -0.1522]], requires_grad=True)

In [41]:
model_.network[2].weight

Parameter containing:
tensor([[ 0.4099, -0.0601, -0.3818]], requires_grad=True)

In [42]:
model_.network[0].bias

Parameter containing:
tensor([ 0.3528, -0.4237,  0.0704], requires_grad=True)

In [43]:
model_.network[2].bias

Parameter containing:
tensor([-0.0253], requires_grad=True)

In [44]:
summary(model_, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model_NN_Seq                             [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [45]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [65]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [66]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [67]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [68]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [69]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [70]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [74]:
X_train_tensor = X_train_tensor.float()  # Convert to float32
y_train_tensor = y_train_tensor.float()  # If labels are floats (e.g., for regression)
y_test_tensor = y_test_tensor.float()
X_test_tensor = X_test_tensor.float()

In [90]:
class RWModel(nn.Module):
    def __init__(self, num_feature):
        super().__init__()
        self.linear = nn.Linear(num_feature, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)

        return out

    # def loss_function(self, y_pred, y):
    #     # Clamp predictions to avoid log(0)
    #     epsilon = 1e-7
    #     y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    
    #     # Calculate loss
    #     loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    #     return loss

In [91]:
learning_rate = 0.1
epochs = 25

In [92]:
loss_function = nn.BCELoss()

In [94]:
model = RWModel(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1 , 1))


  optimizer.zero_grad()
  # backward pass
  loss.backward()

  # # parameters update
  # with torch.no_grad():
  #   model.linear.weight -= learning_rate * model.linear.weight.grad
  #   model.linear.bias -= learning_rate * model.linear.bias.grad

  optimizer.step()
  
    
  # zero gradients
  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7806419134140015
Epoch: 2, Loss: 0.5791077613830566
Epoch: 3, Loss: 0.47401514649391174
Epoch: 4, Loss: 0.41041556000709534
Epoch: 5, Loss: 0.3672930896282196
Epoch: 6, Loss: 0.3357927203178406
Epoch: 7, Loss: 0.3115665018558502
Epoch: 8, Loss: 0.29222431778907776
Epoch: 9, Loss: 0.27633851766586304
Epoch: 10, Loss: 0.26300033926963806
Epoch: 11, Loss: 0.25160178542137146
Epoch: 12, Loss: 0.24171943962574005
Epoch: 13, Loss: 0.23304858803749084
Epoch: 14, Loss: 0.2253635674715042
Epoch: 15, Loss: 0.21849346160888672
Epoch: 16, Loss: 0.2123061865568161
Epoch: 17, Loss: 0.20669764280319214
Epoch: 18, Loss: 0.20158463716506958
Epoch: 19, Loss: 0.1968998908996582
Epoch: 20, Loss: 0.19258801639080048
Epoch: 21, Loss: 0.1886032074689865
Epoch: 22, Loss: 0.18490709364414215
Epoch: 23, Loss: 0.1814672350883484
Epoch: 24, Loss: 0.17825599014759064
Epoch: 25, Loss: 0.17524972558021545


In [96]:
with torch.no_grad():
  y_pred = model(X_test_tensor)
  y_pred = (y_pred > .9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5761772990226746
